import {
  IconAlertTriangle,
  IconArrowRight,
  IconBrandEnvato,
  IconBrandGithub,
  IconBrandTwitter,
  IconBriefcase,
  IconBuilding,
  IconCalendar,
  IconCalendarEvent,
  IconCategory,
  IconChartDots,
  IconChartLine,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconClipboardCheck,
  IconCommand,
  IconCreditCard,
  IconDeviceLaptop,
  IconDotsVertical,
  IconFile,
  IconFileText,
  IconHeadset,
  IconHelpCircle,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLoader2,
  IconLogin,
  IconMapPinFilled,
  IconMoon,
  IconPhoto,
  IconPlus,
  IconProps,
  IconSettings,
  IconStack3,
  IconSun,
  IconTags,
  IconTicket,
  IconTrash,
  IconUserCircle,
  IconUserEdit,
  IconUsers,
  IconWorld,
  IconX
} from '@tabler/icons-react';
import { PieChartIcon } from 'lucide-react';
import React from 'react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // Core navigation icons - each unique
  dashboard: IconLayoutDashboard,
  support: IconHeadset,
  statistics: PieChartIcon,
  clients: IconUsers,
  userPen: IconUserEdit,
  services: IconStack3,
  resource: IconBrandEnvato,
  task: IconClipboardCheck,
  event: IconCalendarEvent,

  // Settings dropdown icons
  world: IconWorld,
  building: IconBuilding,
  categories: IconCategory,
  ticket: IconTicket,
  tags: IconTags,
  metrics: IconChartLine,
  calendar: IconCalendar,
  location: IconMapPinFilled,
  data: IconChartDots,
  settings: IconSettings,

  // UI icons
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  post: IconFileText,
  page: IconFile,
  media: IconPhoto,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUserCircle,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  briefcase: IconBriefcase,
};